"""

This routine has the user check the file lists that were automatically
generated by the pipeline. If the file lists are incorrect, the user
has the ability to manually modify the file lists, then return to the
pipeline.

"""

def nifs_checklists_LP(workdir,rawdir,listnames,datatype,date):

    import sys
    import numpy as np

    print('')
    print('***********************************************************')
    print('Please check the following in '+workdir+':')
    print('')
    
    for ii in range(len(listnames)):
        if np.size(listnames[ii]) > 1:
            for jj in range(np.size(listnames[ii])):
                eachlistname = listnames[ii]
                print(eachlistname[jj])
        elif type(listnames[ii]) is list:
            print((listnames[ii])[0])
        else:
            print(listnames[ii])

    print('')
    print('Make sure the fits files in the above lists are correct '+\
          'by looking at datalist.txt in'+\
          ' %s%s/ and make modifications if needed.' % (rawdir,date))

    print('')
    if datatype == 'daycal':
        print('NOTE, if you would like to combine all arc exposures '+\
              'from a single night/setup together, list all arc exposures'+\
              ' in a single arclist file and delete any other arclist '+\
              'files that may exist. Will use the first arc in the list'+\
              ' for naming the combined arc file.')

    if datatype == 'telluric':
        print('Sky file #1 will be subtracted from telluric file #1, so '+\
              'the number of telluric and sky exposures needs to be the '+\
              'same. It is okay to duplicate sky exposures in skylist. '+\
              'However, skylistshort should contain only unique sky '+\
              'exposures.')

    if datatype == 'galaxy':
        print('The file skylist will be subtracted from the file gallist,'+\
              ' so the number of galaxy and sky exposures needs to be the '+\
              'same. It is okay to duplicate sky exposures in skylist. '+\
              'However, skylistshort should contain only unique sky '+\
              'exposures.')

    if datatype == 'psf':
        print('The file skylist will be subtracted from the file psflist,'+\
              ' so the number of psf and sky exposures needs to be the '+\
              'same. It is okay to duplicate sky exposures in skylist. '+\
              'However, skylistshort should contain only unique sky '+\
              'exposures.')

    if datatype == 'telluric_correction':
        print('NOTE, gallist/psflist will be corrected by the telluric '+\
              'star given in telcorrlist on a line-by-line basis. '+\
              'telcorrlist was generated by searching for '+\
              'the telluric star set observed closest in time to the '+\
              'galaxy/psf exposure; you may want to check/modify based on '+\
              'a match in airmass as well!')

    print('***********************************************************')
        
    response = ''
    while not response.lower() == 'yes' or response.lower() == 'no':

        print('')
        response = raw_input('Are you ready to continue? '+\
                             'Type yes to continue, type no to exit '+\
                             'pipeline. ')

        if response[0:1] == '"' or response[0:1] == "'":
            response = response[1:-1]

        if response.lower() == 'no':
            sys.exit('Okay, quiting the pipeline.')

        if response.lower() != 'yes' and response.lower() != 'no':
            print('That is not one of the choices. Enter again.')
